In [2]:
import pandas as pd

df = pd.read_csv("E:/Downloads/My Projects with datasets/Amazom Phone Reviews Dataset.csv/20191226-reviews.csv")
df.head()

asin           name  rating               date  verified  \
0  B0000SX2UC          Janet       3   October 11, 2005     False   
1  B0000SX2UC     Luke Wyatt       1    January 7, 2004     False   
2  B0000SX2UC         Brooke       5  December 30, 2003     False   
3  B0000SX2UC  amy m. teague       3     March 18, 2004     False   
4  B0000SX2UC  tristazbimmer       4    August 28, 2005     False   

                                          title  \
0                   Def not best, but not worst   
1                   Text Messaging Doesn't Work   
2                               Love This Phone   
3                       Love the Phone, BUT...!   
4  Great phone service and options, lousy case!   

                                                body  helpfulVotes  
0  I had the Samsung A600 for awhile which is abs...           1.0  
1  Due to a software issue between Nokia and Spri...          17.0  
2  This is a great, reliable phone. I also purcha...           5.0  
3  I love the phone and all, because I really did...           1.0  
4  The phone has been great for every purpose it ...           1.0

In [3]:
az = df[['title','body','rating']]
az.head()

title  \
0                   Def not best, but not worst   
1                   Text Messaging Doesn't Work   
2                               Love This Phone   
3                       Love the Phone, BUT...!   
4  Great phone service and options, lousy case!   

                                                body  rating  
0  I had the Samsung A600 for awhile which is abs...       3  
1  Due to a software issue between Nokia and Spri...       1  
2  This is a great, reliable phone. I also purcha...       5  
3  I love the phone and all, because I really did...       3  
4  The phone has been great for every purpose it ...       4

In [4]:
az.loc[:,'reviews'] = az['title']+ ". "+az['body']
az.head()

C:\Users\madda\AppData\Local\Temp\ipykernel_28184\1172219030.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  az.loc[:,'reviews'] = az['title']+ ". "+az['body']


title  \
0                   Def not best, but not worst   
1                   Text Messaging Doesn't Work   
2                               Love This Phone   
3                       Love the Phone, BUT...!   
4  Great phone service and options, lousy case!   

                                                body  rating  \
0  I had the Samsung A600 for awhile which is abs...       3   
1  Due to a software issue between Nokia and Spri...       1   
2  This is a great, reliable phone. I also purcha...       5   
3  I love the phone and all, because I really did...       3   
4  The phone has been great for every purpose it ...       4   

                                             reviews  
0  Def not best, but not worst. I had the Samsung...  
1  Text Messaging Doesn't Work. Due to a software...  
2  Love This Phone. This is a great, reliable pho...  
3  Love the Phone, BUT...!. I love the phone and ...  
4  Great phone service and options, lousy case!. ...

In [5]:
df1 = az[['reviews','rating']]
df1.head()

reviews  rating
0  Def not best, but not worst. I had the Samsung...       3
1  Text Messaging Doesn't Work. Due to a software...       1
2  Love This Phone. This is a great, reliable pho...       5
3  Love the Phone, BUT...!. I love the phone and ...       3
4  Great phone service and options, lousy case!. ...       4

In [6]:
df1.isna().sum()

reviews    49
rating      0
dtype: int64

In [7]:
df1.shape

(67986, 2)

In [8]:
df1 = df1.dropna()

In [9]:
df1.isna().sum()

reviews    0
rating     0
dtype: int64

In [10]:
df1.rating.value_counts()

rating
5    37721
1    12734
4     8817
3     4752
2     3913
Name: count, dtype: int64

# Feature Engineering...

In [11]:
df1.reviews[0]

"Def not best, but not worst. I had the Samsung A600 for awhile which is absolute doo doo. You can read my review on it and detect my rage at the stupid thing. It finally died on me so I used this Nokia phone I bought in a garage sale for $1. I wonder y she sold it so cheap?... Bad: ===> I hate the menu. It takes forever to get to what you want because you have to scroll endlessly. Usually phones have numbered categories so u can simply press the # and get where you want to go. ===> It's a pain to put it on silent or vibrate. If you're in class and it rings, you have to turn it off immediately. There's no fast way to silence the damn thing. Always remember to put it on silent! I learned that the hard way. ===> It's so true about the case. It's a mission to get off and will break ur nails in the process. Also, you'll damage the case each time u try. For some reason the phone started giving me problems once I did succeed in opening it. ===> Buttons could be a bit bigger. Vibration could 

In [12]:
df1.reviews[1]

'Text Messaging Doesn\'t Work. Due to a software issue between Nokia and Sprint this phone\'s text messaging capabilities don\'t work with Sprint\'s system and won\'t until a software patch comes out "some time in the next few months". You will have to spend at least 1 hour with Sprint\'s award winning customer service team to find someone who will admit this to you. The problem is that Nokia designed their phones so that incoming messages are retrieved quickly and then viewed "offline" the way most providers work. Sprint, however, likes to have people hook up to their server first and then stay connected, burning minutes while they check their inbox, compose a reply and wait for the Sprint server to respond so they can send it out. Innovation in money-making at its finest.'

In [13]:
df1.reviews[2]

"Love This Phone. This is a great, reliable phone. I also purchased this phone after my samsung A460 died. The menu is easily comprehendable and speed dialing is available for around 300 numbers. Voice dialing is also a nice feature, but it takes longer than speed dialing. The only thing that bothers me is the games...Nokia seems to have taken snake (1 and 2) off their phones. There is a skydiving game, bowling, and tennis (like pong). The ringers are very nice, and a feature is available to choose a different ringer for each person calling. However, ringtones are not available online to download to this phone. You're pretty much stuck with what you have. There are vibrating ringtones and regular (midi) polyphonic tones. All they need are covers in a reasonable price range..."

In [14]:
import gensim
from gensim.models import Word2Vec

In [15]:
df2 = df1.copy()

In [16]:
df2['reviews'] = df2.reviews.apply(gensim.utils.simple_preprocess)
df2.reviews[0]

['def',
 'not',
 'best',
 'but',
 'not',
 'worst',
 'had',
 'the',
 'samsung',
 'for',
 'awhile',
 'which',
 'is',
 'absolute',
 'doo',
 'doo',
 'you',
 'can',
 'read',
 'my',
 'review',
 'on',
 'it',
 'and',
 'detect',
 'my',
 'rage',
 'at',
 'the',
 'stupid',
 'thing',
 'it',
 'finally',
 'died',
 'on',
 'me',
 'so',
 'used',
 'this',
 'nokia',
 'phone',
 'bought',
 'in',
 'garage',
 'sale',
 'for',
 'wonder',
 'she',
 'sold',
 'it',
 'so',
 'cheap',
 'bad',
 'hate',
 'the',
 'menu',
 'it',
 'takes',
 'forever',
 'to',
 'get',
 'to',
 'what',
 'you',
 'want',
 'because',
 'you',
 'have',
 'to',
 'scroll',
 'endlessly',
 'usually',
 'phones',
 'have',
 'numbered',
 'categories',
 'so',
 'can',
 'simply',
 'press',
 'the',
 'and',
 'get',
 'where',
 'you',
 'want',
 'to',
 'go',
 'it',
 'pain',
 'to',
 'put',
 'it',
 'on',
 'silent',
 'or',
 'vibrate',
 'if',
 'you',
 're',
 'in',
 'class',
 'and',
 'it',
 'rings',
 'you',
 'have',
 'to',
 'turn',
 'it',
 'off',
 'immediately',
 'there

In [17]:
df2.reviews[2]

['love',
 'this',
 'phone',
 'this',
 'is',
 'great',
 'reliable',
 'phone',
 'also',
 'purchased',
 'this',
 'phone',
 'after',
 'my',
 'samsung',
 'died',
 'the',
 'menu',
 'is',
 'easily',
 'comprehendable',
 'and',
 'speed',
 'dialing',
 'is',
 'available',
 'for',
 'around',
 'numbers',
 'voice',
 'dialing',
 'is',
 'also',
 'nice',
 'feature',
 'but',
 'it',
 'takes',
 'longer',
 'than',
 'speed',
 'dialing',
 'the',
 'only',
 'thing',
 'that',
 'bothers',
 'me',
 'is',
 'the',
 'games',
 'nokia',
 'seems',
 'to',
 'have',
 'taken',
 'snake',
 'and',
 'off',
 'their',
 'phones',
 'there',
 'is',
 'skydiving',
 'game',
 'bowling',
 'and',
 'tennis',
 'like',
 'pong',
 'the',
 'ringers',
 'are',
 'very',
 'nice',
 'and',
 'feature',
 'is',
 'available',
 'to',
 'choose',
 'different',
 'ringer',
 'for',
 'each',
 'person',
 'calling',
 'however',
 'ringtones',
 'are',
 'not',
 'available',
 'online',
 'to',
 'download',
 'to',
 'this',
 'phone',
 'you',
 're',
 'pretty',
 'much',
 

In [18]:
df2.head()

reviews  rating
0  [def, not, best, but, not, worst, had, the, sa...       3
1  [text, messaging, doesn, work, due, to, softwa...       1
2  [love, this, phone, this, is, great, reliable,...       5
3  [love, the, phone, but, love, the, phone, and,...       3
4  [great, phone, service, and, options, lousy, c...       4

In [19]:
model = Word2Vec(
    window = 5,
    min_count= 3,
    workers = 4
)

In [20]:
model.build_vocab(df2.reviews)

In [21]:
model.corpus_count

67937

In [22]:
model.wv.most_similar("phone")

[('owning', 0.41102758049964905),
 ('cómo', 0.40582334995269775),
 ('vlc', 0.4016326069831848),
 ('almost', 0.3641005754470825),
 ('knicks', 0.3493119180202484),
 ('hindi', 0.34754106402397156),
 ('eject', 0.34202200174331665),
 ('arise', 0.3313186466693878),
 ('recharging', 0.32620769739151),
 ('location', 0.3260115385055542)]

In [23]:
model.train(df2.reviews, total_examples=model.corpus_count, epochs = 10)

(27660996, 37609450)

In [24]:
# import multiprocessing
# multiprocessing.cpu_count()  ---> This tells the no. of workers to be used in word2vec model

In [25]:
if 'phone' in model.wv:
    print("hi")

hi


In [26]:
df3 = df2.copy()

In [27]:
import numpy as np

def get_review_vector(review, model):
    vectors = [model.wv[word] for word in review if word in model.wv]
    return np.mean(vectors, axis=0) if vectors else np.zeros(model.vector_size)

In [28]:
df3['vectors'] = df3.reviews.apply(lambda x: get_review_vector(x,model))

In [29]:
df3.head()

reviews  rating  \
0  [def, not, best, but, not, worst, had, the, sa...       3   
1  [text, messaging, doesn, work, due, to, softwa...       1   
2  [love, this, phone, this, is, great, reliable,...       5   
3  [love, the, phone, but, love, the, phone, and,...       3   
4  [great, phone, service, and, options, lousy, c...       4   

                                             vectors  
0  [0.09455941, -0.2466124, -0.45979095, -0.23875...  
1  [0.09747698, -0.090319045, -0.6721388, -0.1717...  
2  [-0.03540133, 0.04300792, -0.079255015, -0.175...  
3  [0.09675279, -0.0311747, -0.5729998, -0.214906...  
4  [-0.087484226, -0.16644505, -0.48775983, -0.27...

In [30]:
df3.vectors[0]

array([ 0.09455941, -0.2466124 , -0.45979095, -0.23875733, -0.14941825,
        0.73588634, -0.23912261, -0.60541016,  0.5760251 ,  0.23000167,
       -0.47946322, -0.1255106 , -0.14077078, -0.4936386 ,  0.23966393,
        0.4103109 , -0.3197763 ,  0.930415  ,  0.5707518 ,  0.90470743,
       -0.16786516,  0.20441712, -0.30414668,  0.24092908, -0.13589045,
        0.26791558, -0.316071  ,  0.16334705,  0.38568872, -0.42346707,
        0.34876883,  0.06239476, -0.52471083,  0.3447308 ,  0.17396513,
       -0.5757372 ,  0.11534399,  0.1646648 , -0.2442207 ,  0.15825026,
       -0.48650214,  0.5163108 , -0.36550942, -0.40721577, -0.10651598,
       -0.03490395, -0.05652265,  0.12421232, -0.284376  , -0.5751312 ,
       -0.05721314, -0.2625692 ,  0.04052219,  0.16247086, -0.14105786,
       -0.06385665, -0.10638169, -0.1983588 ,  0.5246915 ,  0.05994965,
       -0.5630905 , -0.22981648, -0.20847204,  0.16255252,  0.29954502,
       -0.42862004,  0.04686455, -0.6550274 , -0.1361489 , -0.50

# Balancing the dataset

In [31]:
df4 = df3.copy()

In [32]:
df4.head()

reviews  rating  \
0  [def, not, best, but, not, worst, had, the, sa...       3   
1  [text, messaging, doesn, work, due, to, softwa...       1   
2  [love, this, phone, this, is, great, reliable,...       5   
3  [love, the, phone, but, love, the, phone, and,...       3   
4  [great, phone, service, and, options, lousy, c...       4   

                                             vectors  
0  [0.09455941, -0.2466124, -0.45979095, -0.23875...  
1  [0.09747698, -0.090319045, -0.6721388, -0.1717...  
2  [-0.03540133, 0.04300792, -0.079255015, -0.175...  
3  [0.09675279, -0.0311747, -0.5729998, -0.214906...  
4  [-0.087484226, -0.16644505, -0.48775983, -0.27...

In [33]:
from imblearn.over_sampling import SMOTE

In [34]:
sampler = SMOTE(random_state = 42)

In [35]:
df4 = df4.drop("reviews",axis = 1)
df4.head()

rating                                            vectors
0       3  [0.09455941, -0.2466124, -0.45979095, -0.23875...
1       1  [0.09747698, -0.090319045, -0.6721388, -0.1717...
2       5  [-0.03540133, 0.04300792, -0.079255015, -0.175...
3       3  [0.09675279, -0.0311747, -0.5729998, -0.214906...
4       4  [-0.087484226, -0.16644505, -0.48775983, -0.27...

In [36]:
X = np.vstack(df4["vectors"].values)
y = df4.rating

In [37]:
x_samp, y_samp= sampler.fit_resample(X,y)

In [38]:
(X.shape,y.shape),(x_samp.shape,y_samp.shape)

(((67937, 100), (67937,)), ((188605, 100), (188605,)))

In [39]:
y_samp.value_counts()

rating
3    37721
1    37721
5    37721
4    37721
2    37721
Name: count, dtype: int64

In [40]:
y_samp.isna().sum()

0

In [41]:
df4.isna().sum()

rating     0
vectors    0
dtype: int64

In [42]:
x_samp[0]

array([ 0.09455941, -0.2466124 , -0.45979095, -0.23875733, -0.14941825,
        0.73588634, -0.23912261, -0.60541016,  0.57602513,  0.23000167,
       -0.47946322, -0.1255106 , -0.14077078, -0.4936386 ,  0.23966393,
        0.41031089, -0.3197763 ,  0.93041497,  0.57075179,  0.90470743,
       -0.16786516,  0.20441712, -0.30414668,  0.24092908, -0.13589045,
        0.26791558, -0.316071  ,  0.16334705,  0.38568872, -0.42346707,
        0.34876883,  0.06239476, -0.52471083,  0.34473079,  0.17396513,
       -0.57573718,  0.11534399,  0.1646648 , -0.2442207 ,  0.15825026,
       -0.48650214,  0.51631081, -0.36550942, -0.40721577, -0.10651598,
       -0.03490395, -0.05652265,  0.12421232, -0.284376  , -0.57513118,
       -0.05721314, -0.26256919,  0.04052219,  0.16247086, -0.14105786,
       -0.06385665, -0.10638169, -0.1983588 ,  0.52469152,  0.05994965,
       -0.5630905 , -0.22981648, -0.20847204,  0.16255252,  0.29954502,
       -0.42862004,  0.04686455, -0.65502739, -0.1361489 , -0.50

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [44]:
(x_samp.shape,y_samp.shape)

((188605, 100), (188605,))

In [45]:
x_train,x_test,y_train,y_test = train_test_split(x_samp,y_samp,test_size = 0.2, random_state = 42)

# Using KNN:

In [46]:
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [47]:
from sklearn.metrics import classification_report

In [48]:
knn_pred = knn.predict(x_test)
print(classification_report(y_test,knn_pred))

              precision    recall  f1-score   support

           1       0.92      0.83      0.88      7611
           2       0.84      0.99      0.91      7453
           3       0.82      0.96      0.89      7560
           4       0.68      0.88      0.77      7591
           5       0.92      0.42      0.58      7506

    accuracy                           0.82     37721
   macro avg       0.84      0.82      0.80     37721
weighted avg       0.84      0.82      0.80     37721



***Testing...***

In [54]:
y_test[:10]

84771     1
41539     5
108976    2
19242     1
90174     1
165770    4
99144     2
38369     2
120116    2
79333     1
Name: rating, dtype: int64

In [55]:
knn.predict(x_test[:10])

array([1, 4, 2, 1, 1, 4, 2, 2, 2, 1], dtype=int64)

# Using Random Forest:

In [49]:
rf = RandomForestClassifier(n_estimators = 30)
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=30)

In [50]:
rf_pred = rf.predict(x_test)
print(classification_report(y_test,rf_pred))

              precision    recall  f1-score   support

           1       0.89      0.93      0.91      7611
           2       0.93      0.95      0.94      7453
           3       0.92      0.93      0.92      7560
           4       0.86      0.86      0.86      7591
           5       0.88      0.80      0.84      7506

    accuracy                           0.89     37721
   macro avg       0.89      0.89      0.89     37721
weighted avg       0.89      0.89      0.89     37721



***Testing...***

In [51]:
y_test[:10]

84771     1
41539     5
108976    2
19242     1
90174     1
165770    4
99144     2
38369     2
120116    2
79333     1
Name: rating, dtype: int64

In [52]:
rf.predict(x_test[:10])

array([1, 5, 2, 1, 1, 4, 2, 2, 2, 1], dtype=int64)

# Using SVM:

In [ ]:
# Its your task. Do it! And comment me in the github by giving me a pull request :)

In [ ]:
svm = SVC(C=1 )
svm.fit(x_train,y_train) 

In [ ]:
svm_pred = svm.predict(x_test)
print(classification_report(y_test,svm_pred))